########################################################################################################################
### 공통 (참고 : http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
########################################################################################################################

# application
application:
  title: @project.groupId@.@project.artifactId@ (@project.version@)

server:
  # embeded tomcat
  port: 8080
  tomcat:
    uri-encoding: UTF-8 # Character encoding to use to decode the URI.

  # SpringBoot default error page disable
  error:
    whitelabel:
      enabled: false

# banner
banner:
  charset: UTF-8 # Banner file encoding.
  location: classpath:config/banner.txt # Banner file location.

# spring
spring:

  # APPLICATION SETTINGS (SpringApplication)
  main:
    show-banner: true

  # IDENTITY (ContextIdApplicationContextInitializer)
  application:
    index: # Application index.
    name: @project.artifactId@

  # AUTO-CONFIGURATION
  autoconfigure:
    exclude: # Auto-configuration classes to exclude.

  # favicon
  mvc.favicon.enabled: false

  #profile 설정을 안했을 시 active profile
  profiles:
    active: local

  # HTTP encoding (HttpEncodingProperties)
  http:
    encoding:
      charset: UTF-8 # the encoding of HTTP requests/responses
      enabled: true # enable http encoding support
      force: true # force the configured encoding

  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    enabled: true # Enable MVC Thymeleaf view resolution.
    cache: true # Enable template caching.
    check-template-location: true # Check that the templates location exists.
    content-type: text/html # Content-Type value.
    encoding: UTF-8 # Template encoding.
    mode: LEGACYHTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    suffix: .html # Suffix that gets appended to view names when building a URL.

  # AOP -> TODO AOP 는 나중에 손보기
#  aop:
#    auto: true # Add @EnableAspectJAutoProxy.
#    proxy-target-class: false # Whether subclass-based (CGLIB) proxies are to be created (true) as opposed to standard Java interface-based proxies (false).

  # DEVTOOLS (DevToolsProperties)
  devtools:
    restart:
      enabled: true # Enable automatic restart.
      exclude: META-INF/maven/**,META-INF/resources/**,resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties # Patterns that should be excluded from triggering a full restart.
      poll-interval: 1000 # Amount of time (in milliseconds) to wait between polling for classpath changes.
      quiet-period: 400 # Amount of quiet time (in milliseconds) required without any classpath changes before a restart is triggered.

# logging
logging:
  config: classpath:config/logback/logback.xml

# [sample] application properties
sample:
  props:
    project:
      title: Sample
    admins:
      -
        id: admin
        pw: admin
      -
        id: admin2
        pw: admin2

---

########################################################################################################################
### 실/운영
########################################################################################################################
spring:
  profiles: prod

# [sample] application properties
sample:
  props:
    testmsg:
      - 실/운영 환경에서의 테스트 메세지 1
      - 실/운영 환경에서의 테스트 메세지 2

---

########################################################################################################################
### 테스트
########################################################################################################################
spring:
  profiles: test

server:
  port: 8888

# [sample] application properties
sample:
  props:
    testmsg:
      - 테스트 환경에서의 테스트 메세지 1
      - 테스트 환경에서의 테스트 메세지 2

---

########################################################################################################################
### 로컬
########################################################################################################################
spring:
  profiles: local
  thymeleaf:
      cache: false # Enable template caching.

server:
  port: 8080

# [sample] application properties
sample:
  props:
    testmsg:
      - 로컬 환경에서의 테스트 메세지 1
      - 로컬 환경에서의 테스트 메세지 2

...